import * as React from 'react';

import { Offer } from './OfferBox';
import { Autocomplete, Box, Button, Container, IconButton, Paper, Slider, TextField, Typography } from '@mui/material';
import { ServiceBayLogo } from 'modules/ServiceBayLogo';
import { FilterAltOff, FilterList, Search } from '@mui/icons-material';
import { OfferRow } from './OfferRow';
import { useRouter } from 'next/router';

const messages = [
  {
    id: 1,
    primary: 'Brunch this week?',
    secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 2,
    primary: 'Birthday Gift',
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: '/static/images/avatar/1.jpg',
  },
  {
    id: 3,
    primary: 'Recipe to try',
    secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
    person: '/static/images/avatar/2.jpg',
  },
  {
    id: 4,
    primary: 'Yes!',
    secondary: 'I have the tickets to the ReactConf for this year.',
    person: '/static/images/avatar/3.jpg',
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
    person: '/static/images/avatar/4.jpg',
  },
  {
    id: 6,
    primary: 'Discussion',
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: '/static/images/avatar/5.jpg',
  },
  {
    id: 7,
    primary: 'Summer BBQ',
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: '/static/images/avatar/1.jpg',
  },
];

// eslint-disable-next-line import/no-default-export
export function Listings() {
  const router = useRouter();
  return (
    <React.Fragment>
      <Box className="banner static-beach_bar">
        <div className="static-beach_bar__waves" />
        <div className="static-beach_bar__sand static-beach_bar__sand--background" />
        <div className="static-beach_bar__sand static-beach_bar__sand--foreground" />
        <Container maxWidth="xl">
          <Box className="w-full h-[200px] flex text-center justify-center items-center">
            <Box className="flex z-10">
              <Typography className="font-bukhari text-[4.5rem] leading-[4.5rem] text-[#121212]">
                {router.query.category ? router.query.category : 'Listings'}
              </Typography>
            </Box>
          </Box>
        </Container>
      </Box>

      <Container maxWidth="xl" className="pt-10 flex flex-col gap-5">
        <Paper className="w-full flex h-[60px] items-center justify-center gap-3 px-3">
          <TextField
            label="What are you lookign for?"
            variant="outlined"
            value=" "
            className="w-[250px]"
            inputProps={{ className: 'h-[6px]' }}
          />
          <Button variant="contained" color="secondary" startIcon={<Search />}>
            Search
          </Button>
          <Box className="flex flex-1"></Box>
          <IconButton>
            <FilterList></FilterList>
          </IconButton>
        </Paper>
        <Box className="flex flex-row gap-5">
          <Box className="w-[250px]" sx={{ display: { sm: 'none', md: 'flex' } }}>
            <Paper>
              <Box className="flex flex-col gap-5 p-5 w-[250px]">
                <Box className="flex flex-row items-center">
                  <Typography className="font-bold flex-1">FILTERS</Typography>
                  <IconButton>
                    <FilterAltOff></FilterAltOff>
                  </IconButton>
                </Box>
                <Typography className="font-bold">Price range</Typography>
                <Slider
                  getAriaLabel={() => 'Minimum distance'}
                  value={[10, 50]}
                  onChange={() => {}}
                  valueLabelDisplay="auto"
                  disableSwap
                />
              </Box>
            </Paper>
          </Box>
          <Box className="flex flex-wrap flex-row gap-5 justify-evenly">
            {messages.map(({ id, primary, secondary }) => (
              <React.Fragment key={id}>
                <OfferRow description={secondary} title={primary} />
              </React.Fragment>
            ))}
          </Box>
        </Box>
      </Container>
    </React.Fragment>
  );
}
